// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Northwind))]
    [Migration("20231121085303_add data")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Database.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("d4181d3c-1e2f-4ed9-8f16-1bade0cc3c8e"),
                            CategoryName = "Handphone",
                            Description = "Ini category Handphone"
                        },
                        new
                        {
                            CategoryId = new Guid("2fc94449-99cb-481e-826f-633af1e38981"),
                            CategoryName = "Buah",
                            Description = "Ini category Buah"
                        });
                });

            modelBuilder.Entity("Database.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("ed473b45-1055-4513-8b1b-c50a697ed387"),
                            CategoryId = new Guid("d4181d3c-1e2f-4ed9-8f16-1bade0cc3c8e"),
                            Description = "Ini xiaomi",
                            ProductName = "Xiaomi"
                        },
                        new
                        {
                            ProductId = new Guid("7f0809f6-c836-40fd-bf40-2f43c6a48d36"),
                            CategoryId = new Guid("2fc94449-99cb-481e-826f-633af1e38981"),
                            Description = "Ini Pisang",
                            ProductName = "Pisang"
                        });
                });

            modelBuilder.Entity("Database.Product", b =>
                {
                    b.HasOne("Database.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Database.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
